// LOCALHOST 
### 
GET http://localhost:8080/contacts 
### 
GET http://localhost:8080/contacts/6276d3847f064b186132867a 
### 
GET http://localhost:8080/contacts/6276d3847f064b186132867b 
### 
GET http://localhost:8080/contacts/6276d3847f064b186132867c

// PRODUCTION Deploy 
### 
GET https://cse341-instructor.herokuapp.com/contacts 
### 
GET https://cse341-instructor.herokuapp.com/contacts/622023f642f9ab4cd6e060b2 
### 
GET https://cse341-instructor.herokuapp.com/contacts/622023f642f9ab4cd6e060b3 
### 
GET https://cse341-instructor.herokuapp.com/contacts/622023f642f9ab4cd6e060b4